server:
  port: 9001

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
#        server-addr: 127.0.0.1:8848 #配置Nacos地址
        server-addr: 192.168.1.8:1111 #配置Nacos地址


management:
  endpoints:
    web:
      exposure:
        include: '*'

